cataclysm/armor/urls.py
from django.urls import path

from . import views

app_name = 'armor'

urlpatterns = [
    path('', views.ArmorListView.as_view(), name='index'),
    path('add/', views.ArmorCreateView.as_view(), name='add'),
    path('<int:pk>/', views.ArmorDetailView.as_view(), name='detail'),
]

cataclysm/cataclysm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("landing.urls")),
    path('armor/', include("armor.urls")),
    path('events/', include("events.urls")),
    path('factions/', include("factions.urls")),
    path('people/', include('people.urls')),
    path('species/', include("species.urls")),
    path('weapons/', include("weapons.urls")),
    path('worlds/', include("worlds.urls")),
    path('ships/', include("ships.urls")),
    # legacy/alias route used in some templates - include with a distinct namespace to avoid duplicate registration
    path('starships/', include(("ships.urls", "ships"), namespace='starships')),
    path('vehicles/', include("vehicles.urls")),
    path('party/', include("party.urls")),
    path('adminflow/', include("adminflow.urls")),
    path('mindmaps/', include("mindmaps.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cataclysm/weapons/urls.py
from django.urls import path

from . import views

app_name = 'weapons'

urlpatterns = [
    path('', views.WeaponListView.as_view(), name='index'),
    path('add/', views.WeaponCreateView.as_view(), name='add'),
    path('<int:pk>/', views.WeaponDetailView.as_view(), name='detail'),
]

cataclysm/weapons/models.py
from django.db import models

class Weapon(models.Model):
    name = models.CharField(max_length=100)
    weapon_type = models.CharField(max_length=50)
    damage = models.CharField(max_length=20)
    critical = models.CharField(max_length=20)
    range_increment = models.IntegerField()
    capacity = models.IntegerField()
    usage = models.CharField(max_length=50)
    special_properties = models.TextField()
    secondary_weapon = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)
    weight = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    hidden = models.BooleanField(default=False)

    def __str__(self):
        return self.name

cataclysm/weapons/views.py
from cataclysm.cataclysm.views import StaticIndexView

index = StaticIndexView.as_view(app_label="weapons")

cataclysm/weapons/templates/weapons/add_object.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="/static/css/sci-fi-form.css">
<div class="container sci-fi-form-container" style="max-width:900px; margin-top:20px;">
  <h1>Add Weapon</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save Weapon</button>
  </form>
</div>
{% endblock %}

cataclysm/weapons/templates/weapons/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>{{ object.name|default:'Weapon' }}</h1>
  <p>{{ object.description|default:'No description available.' }}</p>
  <a href="{% url 'weapons:index' %}">Back</a>
</div>
{% endblock %}

cataclysm/weapons/templates/weapons/weapons.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="list-header index_menu">
	<h1 class="app_name">Weapons</h1>
	<a href="{% url 'weapons:add' %}" class="btn btn-primary">Add Weapon</a>
</div>
<table class="table table-striped sci-fi-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Type</th>
			<th>Damage</th>
			<th>Critical</th>
			<th>Range</th>
			<th>Capacity</th>
			<th>Weight</th>
			<th>Hidden</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	{% for w in object_list %}
		<tr>
			<td>{{ w.name }}</td>
			<td>{{ w.weapon_type }}</td>
			<td>{{ w.damage }}</td>
			<td>{{ w.critical }}</td>
			<td>{{ w.range_increment }}</td>
			<td>{{ w.capacity }}</td>
			<td>{{ w.weight }}</td>
			<td>{{ w.hidden }}</td>
			<td><a href="{% url 'weapons:detail' w.pk %}">View</a></td>
		</tr>
	{% empty %}
		<tr><td colspan="9">No weapons yet</td></tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}