cataclysm/armor/urls.py
from django.urls import path

from . import views

app_name = 'armor'

urlpatterns = [
    path('', views.ArmorListView.as_view(), name='index'),
    path('add/', views.ArmorCreateView.as_view(), name='add'),
    path('<int:pk>/', views.ArmorDetailView.as_view(), name='detail'),
]

cataclysm/cataclysm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("landing.urls")),
    path('armor/', include("armor.urls")),
    path('events/', include("events.urls")),
    path('factions/', include("factions.urls")),
    path('people/', include('people.urls')),
    path('species/', include("species.urls")),
    path('weapons/', include("weapons.urls")),
    path('worlds/', include("worlds.urls")),
    path('ships/', include("ships.urls")),
    # legacy/alias route used in some templates - include with a distinct namespace to avoid duplicate registration
    path('starships/', include(("ships.urls", "ships"), namespace='starships')),
    path('vehicles/', include("vehicles.urls")),
    path('party/', include("party.urls")),
    path('adminflow/', include("adminflow.urls")),
    path('mindmaps/', include("mindmaps.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cataclysm/worlds/urls.py
from django.urls import path

from . import views

app_name = 'worlds'

urlpatterns = [
    path('', views.WorldListView.as_view(), name='index'),
    path('add/', views.WorldCreateView.as_view(), name='add'),
    path('<int:pk>/', views.WorldDetailView.as_view(), name='detail'),
]

cataclysm/worlds/models.py
from django.db import models

class World(models.Model):
    name = models.CharField(max_length=50)
    system = models.CharField(max_length=50)
    planet_class = models.CharField(max_length=2)
    moons = models.IntegerField()
    colonized = models.BooleanField()
    terraformed = models.BooleanField()
    contains_flora = models.BooleanField()
    contains_fauna = models.BooleanField()
    contains_sentient_life = models.BooleanField()
    special_traits = models.JSONField()
    points_of_interest = models.JSONField()
    hidden = models.BooleanField(default=False)

    def __str__(self):
        return self.name

cataclysm/worlds/views.py
from cataclysm.cataclysm.views import StaticIndexView

index = StaticIndexView.as_view(app_label="worlds")

cataclysm/worlds/templates/worlds/add_object.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="/static/css/sci-fi-form.css">
<div class="container sci-fi-form-container" style="max-width:900px; margin-top:24px;">
  <h1>Add World</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save World</button>
  </form>
</div>
{% endblock %}

cataclysm/worlds/templates/worlds/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>{{ object.name|default:'World' }}</h1>
  <p>System: {{ object.system|default:'-' }}</p>
  <p>Planet class: {{ object.planet_class|default:'-' }}</p>
  <a href="{% url 'worlds:index' %}">Back</a>
</div>
{% endblock %}

cataclysm/worlds/templates/worlds/worlds.html
{% extends 'base.html' %}
{% block content %}
<div class="list-header index_menu">
	<h1 class="app_name">Worlds</h1>
	<a href="{% url 'worlds:add' %}" class="btn btn-primary">Add World</a>
</div>
<table class="table table-hover sci-fi-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>System</th>
			<th>Class</th>
			<th>Moons</th>
			<th>Colonized</th>
			<th>Terraform</th>
			<th>Flora/Fauna</th>
			<th>Hidden</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	{% for w in object_list %}
		<tr>
			<td>{{ w.name }}</td>
			<td>{{ w.system }}</td>
			<td>{{ w.planet_class }}</td>
			<td>{{ w.moons }}</td>
			<td>{{ w.colonized }}</td>
			<td>{{ w.terraformed }}</td>
			<td>{% if w.contains_flora %}Flora {% endif %}{% if w.contains_fauna %}Fauna{% endif %}</td>
			<td>{{ w.hidden }}</td>
			<td><a href="{% url 'worlds:detail' w.pk %}">View</a></td>
		</tr>
	{% empty %}
		<tr><td colspan="9">No worlds yet</td></tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}