cataclysm/armor/urls.py
from django.urls import path

from . import views

app_name = 'armor'

urlpatterns = [
    path('', views.ArmorListView.as_view(), name='index'),
    path('add/', views.ArmorCreateView.as_view(), name='add'),
    path('<int:pk>/', views.ArmorDetailView.as_view(), name='detail'),
]

cataclysm/cataclysm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("landing.urls")),
    path('armor/', include("armor.urls")),
    path('events/', include("events.urls")),
    path('factions/', include("factions.urls")),
    path('people/', include('people.urls')),
    path('species/', include("species.urls")),
    path('weapons/', include("weapons.urls")),
    path('worlds/', include("worlds.urls")),
    path('ships/', include("ships.urls")),
    # legacy/alias route used in some templates - include with a distinct namespace to avoid duplicate registration
    path('starships/', include(("ships.urls", "ships"), namespace='starships')),
    path('vehicles/', include("vehicles.urls")),
    path('party/', include("party.urls")),
    path('adminflow/', include("adminflow.urls")),
    path('mindmaps/', include("mindmaps.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cataclysm/species/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("index/", views.index, name="index"),
    path("add_species/", views.add_species, name="add_species"),
    path("<int:id>/", views.species_page, name="species_page"),
    path("edit/<int:id>", views.edit_species, name="edit_species"),
]

cataclysm/species/models.py
from django.db import models

class Species(models.Model):
    class Meta:
        app_label = 'species'
    SIZE_CHOICES = [
        ('diminutive', 'Diminutive'),
        ('tiny', 'Tiny'),
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
        ('huge', 'Huge'),
        ('gargantuan', 'Gargantuan'),
        ('colossal', 'Colossal'),
        ('planetary', 'Planetary'),
    ]
    TYPE_CHOICES = [
        ('animal','Animal'),
        ('biotech','Bio-Tech'),
        ('plant','Plant'),
        ('metamorph','Metamorph'),
        ('unique','Unique'),
    ]
    AIR_CHOICES = [
        ('oxygen','Oxygen'),
        ('nitrogen','Nitrogen'),
        ('carbon-dioxide','Carbon Dioxide'),
        ('argon','Argon'),
        ('unique','Unique'),
        ('xenon','Xenon'),
        ('dihydrogen-oxide','Dihydrogen Oxide'),
        ('hydrogen','Hydrogen'),
        ('helium','Helium'),
        ('neon','Neon'),
    ]
    REPRODUCTIVE_CHOICES = [
        ('standard','Standard'),
        ('asexual','Asexual'),
        ('fission','Fission'),
        ('clone','Clone'),
        ('unique','Unique'),
    ]
    GRAVITY_CHOICES = [
        ('light','Light'),
        ('standard','Standard'),
        ('heavy','Heavy'),
    ]
    ACCORD_STATUS_CHOICES = [
        ('founder','Founding Member'),
        ('ally','Ally'),
        ('member','Member'),
        ('peace','Peace Treaty'),
        ('enemy','Enemy'),
        ('nuetral','Nuetral'),
        ('unknown','Unknown'),
        ('undiscovered','Undiscovered'),
    ]
    SOCIETY_CHOICES = [
        ('monarchy','Monarchy'),
        ('theocracy','Theocracy'),
        ('democracy','Democracy'),
        ('caste','Caste'),
        ('tribal','Tribal'),
        ('free','Free'),
        ('unknown','Unknown'),
        ('empire','Empire'),
        ('conglomerate','Conglomerate'),
        ('aristocracy','Aristocracy'),
        ('multiple','Multiple'),
        ('anarchy','Anarchy'),
        ('technocracy','Technocracy'),
    ]
    LOCOMOTION_CHOICES = [
        ('bipedal','Bipedal'),
        ('tentacle','Tentacle'),
        ('multiped','Multiped'),
        ('flight','Flight'),
        ('serpentine','Serpentine'),
        ('metamorph','Metamorph'),
        ('float','Float'),
        ('quadruped','Quadruped'),
        ('octoped','Octoped'),
    ]
    name = models.CharField(max_length=100)
    home_world = models.CharField(max_length=100, blank=True, null=True)
    society = models.CharField(max_length=50, choices=SOCIETY_CHOICES, blank=True, null=True)
    accord_status = models.CharField(max_length=20, choices=ACCORD_STATUS_CHOICES, blank=True, null=True)
    background = models.TextField(blank=True, null=True)
    sociology = models.TextField(blank=True, null=True)
    physiology = models.TextField(blank=True, null=True)
    racial_traits = models.JSONField(blank=True, null=True)
    size = models.CharField(max_length=20, choices=SIZE_CHOICES, blank=True, null=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, blank=True, null=True)
    air = models.CharField(max_length=50, choices=AIR_CHOICES, blank=True, null=True)
    reproduction_method = models.CharField(max_length=20, choices=REPRODUCTIVE_CHOICES, blank=True, null=True)
    hours_of_sleep = models.IntegerField(null=True, blank=True)
    days_without_food = models.IntegerField(null=True, blank=True)
    days_without_water = models.IntegerField(null=True, blank=True)
    strength_rating = models.IntegerField(null=True, blank=True)
    toughness_rating = models.IntegerField(null=True, blank=True)
    speed_rating = models.IntegerField(null=True, blank=True)
    intelligence_rating = models.IntegerField(null=True, blank=True)
    natural_weapons = models.BooleanField(default=False)
    natural_armor = models.BooleanField(default=False)
    can_fly = models.BooleanField(default=False)
    aquatic = models.BooleanField(default=False)
    amphibious = models.BooleanField(default=False)
    telepathic = models.BooleanField(default=False)
    psionic = models.BooleanField(default=False)
    gravity = models.CharField(max_length=15, choices=GRAVITY_CHOICES, blank=True, null=True)
    special_abilities = models.JSONField(blank=True, null=True)
    locomotion_method = models.CharField(max_length=20, choices=LOCOMOTION_CHOICES, blank=True, null=True)
    image = models.ImageField(upload_to='species/images/', null=True, blank=True)
    hidden = models.BooleanField(default=False)

    def __str__(self):
        return self.name

cataclysm/species/forms.py
from django import forms
from .models import Species

class SpeciesForm(forms.ModelForm):
    class Meta:
        model = Species
        fields = [
            'name',
            'home_world',
            'society',
            'accord_status',
            'background',
            'sociology',
            'physiology',
            'racial_traits',
            'size',
            'type',
            'air',
            'reproduction_method',
            'hours_of_sleep',
            'days_without_food',
            'days_without_water',
            'strength_rating',
            'toughness_rating',
            'speed_rating',
            'intelligence_rating',
            'natural_weapons',
            'natural_armor',
            'can_fly',
            'aquatic',
            'amphibious',
            'telepathic',
            'psionic',
            'gravity',
            'special_abilities',
            'locomotion_method',
            'image',
            'hidden',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Make most fields optional on the form level; keep `name` required
        for fname, field in self.fields.items():
            if fname == 'name':
                field.required = True
            else:
                field.required = False

cataclysm/species/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from species.models import Species
from species.forms import SpeciesForm


def index(request):
    # Sorting support via ?sort=field or ?sort=-field (prefix '-' for descending)
    sort_param = request.GET.get('sort', '').strip()
    allowed = {
        'name': 'name',
        'size': 'size',
        'home_world': 'home_world',
        'type': 'type',
        'accord_status': 'accord_status',
        'strength': 'strength_rating',
        'toughness': 'toughness_rating',
        'speed': 'speed_rating',
        'intelligence': 'intelligence_rating',
    }

    order_by = 'name'
    current_sort_field = ''
    current_sort_dir = 'asc'
    if sort_param:
        direction = 'asc'
        field = sort_param
        if sort_param.startswith('-'):
            direction = 'desc'
            field = sort_param[1:]

        mapped = allowed.get(field)
        if mapped:
            order_by = ('-' if direction == 'desc' else '') + mapped
            current_sort_field = field
            current_sort_dir = direction

    species_list = Species.objects.all().order_by(order_by)
    context = {
        'species_list': species_list,
        'current_sort_field': current_sort_field,
        'current_sort_dir': current_sort_dir,
    }
    return render(request, 'species_index.html', context)


def species_page(request, id):
    current_species = Species.objects.get(id=id)
    context = {
        'current_species': current_species,
    }
    return render(request, 'species.html', context)

def add(request):
    if request.method == 'POST':
        form = SpeciesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_page')  # Redirect to a success page after adding the object
    else:
        form = SpeciesForm()

    return render(request, 'species/add_object.html', {'form': form})

def edit_species(request, id):
    species = Species.objects.get(id=id)
    if request.method == 'POST':
        form = SpeciesForm(request.POST, instance=species)
        if form.is_valid():
            form.save()
            return redirect('success_page')  # Redirect to a success page after adding the object
    else:
        form = SpeciesForm(instance=species)

    return render(request, 'species/add_object.html', {'form': form})

cataclysm/species/templates/add_object.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="/static/css/sci-fi-form.css">
<div class="container sci-fi-form-container" style="max-width:900px; margin-top:24px;">
	<h1>Add Species</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-primary">Save Species</button>
	</form>
</div>
{% endblock %}

cataclysm/species/templates/species_index.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load group_check %}

{% block content %}
<link rel="stylesheet" href="/static/css/sci-fi-form.css">
<div class="container" style="margin-top:20px;">
    <div class="list-header index_menu">
        <h1 class="app_name">Species Index</h1>
        <a class="btn btn-primary" href="{% url 'add' %}">Add Species</a>
    </div>
    <table class="sci-fi-list">
        <thead>
            <tr>
                <th><a href="?sort={% if current_sort_field == 'name' and current_sort_dir == 'asc' %}-name{% else %}name{% endif %}">Name {% if current_sort_field == 'name' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'size' and current_sort_dir == 'asc' %}-size{% else %}size{% endif %}">Size {% if current_sort_field == 'size' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'home_world' and current_sort_dir == 'asc' %}-home_world{% else %}home_world{% endif %}">Home World {% if current_sort_field == 'home_world' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'type' and current_sort_dir == 'asc' %}-type{% else %}type{% endif %}">Type {% if current_sort_field == 'type' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'accord_status' and current_sort_dir == 'asc' %}-accord_status{% else %}accord_status{% endif %}">Accord Standing {% if current_sort_field == 'accord_status' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'strength' and current_sort_dir == 'asc' %}-strength{% else %}strength{% endif %}">Strength {% if current_sort_field == 'strength' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'toughness' and current_sort_dir == 'asc' %}-toughness{% else %}toughness{% endif %}">Toughness {% if current_sort_field == 'toughness' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'speed' and current_sort_dir == 'asc' %}-speed{% else %}speed{% endif %}">Speed {% if current_sort_field == 'speed' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                <th><a href="?sort={% if current_sort_field == 'intelligence' and current_sort_dir == 'asc' %}-intelligence{% else %}intelligence{% endif %}">Intelligence {% if current_sort_field == 'intelligence' %}{% if current_sort_dir == 'asc' %}▲{% else %}▼{% endif %}{% endif %}</a></th>
                {% if request.user|has_group:'admins' %}
                    <th>Hidden</th>
                {% endif %}
                
            </tr>
        </thead>
        <tbody>
            {% for species in species_list %}
                {% if not species.hidden %}
                    <tr>
                        <td><a href="{% url 'species_page' species.id %}">{{ species.name }}</a></td>
                        <td>{{ species.get_size_display }}</td>
                        <td>{{ species.home_world }}</td>
                        <td>{{ species.get_type_display }}</td>
                        <td>{{ species.get_accord_status_display }}</td>
                        <td>
                            <div class="rating-bar" style="width: {{species.strength_rating|mul:10}}%">&nbsp;{{ species.strength_rating }}</div>
                        </td>
                        <td>
                            <div class="rating-bar" style="width: {{species.toughness_rating|mul:10}}%">&nbsp;{{ species.toughness_rating }}</div>
                        </td>
                        <td>
                            <div class="rating-bar" style="width: {{species.speed_rating|mul:10}}%">&nbsp;{{ species.speed_rating }}</div>
                        </td>
                        <td>
                            <div class="rating-bar" style="width: {{species.intelligence_rating|mul:10}}%">&nbsp;{{ species.intelligence_rating }}</div>
                        </td>
                        {% if request.user|has_group:'admins' %}
                            <td>{{ species.hidden }}</td>
                        {% endif %}
                    </tr>
                {% endif %}
            {% empty %}
                <tr>
                    <td colspan="3">No species found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}