cataclysm/armor/urls.py
from django.urls import path

from . import views

app_name = 'armor'

urlpatterns = [
    path('', views.ArmorListView.as_view(), name='index'),
    path('add/', views.ArmorCreateView.as_view(), name='add'),
    path('<int:pk>/', views.ArmorDetailView.as_view(), name='detail'),
]

cataclysm/cataclysm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("landing.urls")),
    path('armor/', include("armor.urls")),
    path('events/', include("events.urls")),
    path('factions/', include("factions.urls")),
    path('people/', include('people.urls')),
    path('species/', include("species.urls")),
    path('weapons/', include("weapons.urls")),
    path('worlds/', include("worlds.urls")),
    path('ships/', include("ships.urls")),
    # legacy/alias route used in some templates - include with a distinct namespace to avoid duplicate registration
    path('starships/', include(("ships.urls", "ships"), namespace='starships')),
    path('vehicles/', include("vehicles.urls")),
    path('party/', include("party.urls")),
    path('adminflow/', include("adminflow.urls")),
    path('mindmaps/', include("mindmaps.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cataclysm/vehicles/urls.py
from django.urls import path
from . import views

app_name = 'vehicles'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('<int:pk>/', views.detail, name='detail'),
]

cataclysm/vehicles/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'vehicles/vehicles.html', {'object_list': []})


def detail(request, pk):
    return render(request, 'vehicles/detail.html', {'object': None})


def add(request):
    return render(request, 'vehicles/add_object.html', {})

cataclysm/vehicles/templates/vehicles/add_object.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="/static/css/sci-fi-form.css">
<div class="container sci-fi-form-container" style="max-width:900px; margin-top:24px;">
  <h1>Add Vehicle</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save Vehicle</button>
  </form>
</div>
{% endblock %}

cataclysm/vehicles/templates/vehicles/vehicles.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="/static/css/sci-fi-form.css">
<div class="container" style="margin-top:20px;">
    <div class="list-header index_menu">
        <h1 class="app_name">Vehicles</h1>
        <a class="btn btn-primary" href="{% url 'vehicles:add' %}">Add Vehicle</a>
    </div>
  <table class="sci-fi-list" style="margin-top:12px; width:100%;">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Seats</th>
        <th>Hidden</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for obj in object_list %}
      <tr>
        <td>{{ obj.name }}</td>
        <td>{{ obj.vehicle_type|default:'' }}</td>
        <td>{{ obj.seats|default:'-' }}</td>
        <td>{{ obj.hidden|default:False }}</td>
        <td><a href="{% url 'vehicles:detail' obj.pk %}">View</a></td>
      </tr>
      {% empty %}
      <tr><td colspan="5">No vehicles found.</td></tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}